### ISSUE TITLE
ImportError: No module named _ffi

### ISSUE THREAD

**Issue by andresriancho** [davidblewett/rure-python#15]
```
$ pip install rure
Requirement already satisfied: rure in /home/eth/tools/virtualenvs/w3af/lib/python2.7/site-packages (0.2.0)
Requirement already satisfied: six in /home/eth/tools/virtualenvs/w3af/lib/python2.7/site-packages (from rure) (1.11.0)
Requirement already satisfied: cffi>=1.5.0 in /home/eth/tools/virtualenvs/w3af/lib/python2.7/site-packages (from rure) (1.11.5)
Requirement already satisfied: pycparser in /home/eth/tools/virtualenvs/w3af/lib/python2.7/site-packages (from cffi>=1.5.0->rure) (2.18)

$ python -c 'import rure'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "rure/__init__.py", line 3, in <module>
    from rure.lib import Rure, RureSet
  File "rure/lib.py", line 5, in <module>
    from rure._ffi import ffi
ImportError: No module named _ffi
```

**Comment by davidblewett** [comment]
@andresriancho are you running this from inside the directory where you cloned this repo?
